# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Norminette
        run: |
             python3 -m pip install --upgrade pip setuptools
             python3 -m pip install norminette
      - name: Run Norminette
        run: norminette srcs
      - name: Install llvm clang
        run: brew install llvm
      - name: USLEEP_TIME 0
        run: sed -i "" "/USLEEP_TIME/s/[0-9]\{1,\}/0/" includes/term3d.h
      - name: make address
        run: |
              make address
              ./term3d figures/torus.3d
      - name: make leak
        run: |
              make leak
              ./term3d figures/torus.3d
